# -*- coding: utf-8 -*-
"""NLP_HW4_NCCU_111307051

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2knThIKdsOzBpdUAG3ye68NMw26ADH5

# RAG using Langchain

## Packages loading & import
"""

# When running in Google Colab, you may need to install dependencies manually, e.g.:
# !pip install "langchain-core>=0.2.0,<0.3.0" "langchain>=0.2.0,<0.3.0" "langchain-community>=0.2.0,<0.3.0" \
#              "langchain-huggingface>=0.0.3,<0.1.0" "langchain-chroma>=0.1.0,<0.2.0" "langchain-ollama>=0.1.0,<0.2.0" \
#              "langchain-text-splitters>=0.2.0,<0.3.0" "transformers>=4.39.0" "accelerate>=0.28.0" "sentence-transformers" \
#              "rank-bm25" "huggingface_hub" "tqdm" "beautifulsoup4"

import os
import json
import bs4
import nltk
import torch
import pickle
import numpy as np

# from pyserini.index import IndexWriter
# from pyserini.search import SimpleSearcher
from numpy.linalg import norm
from rank_bm25 import BM25Okapi
from nltk.tokenize import word_tokenize

from langchain_community.llms import Ollama
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain
from langchain.vectorstores import Chroma
from sentence_transformers import SentenceTransformer
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.embeddings import JinaEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter, TokenTextSplitter
from langchain.docstore.document import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_community.document_loaders import WebBaseLoader
from transformers import AutoModel, AutoModelForCausalLM, AutoTokenizer

from tqdm import tqdm

nltk.download('punkt')
nltk.download('punkt_tab')

"""## Hugging face login
- Please apply the model first: https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct
- If you haven't been granted access to this model, you can use other LLM model that doesn't have to apply.
- You must save the hf token otherwise you need to regenrate the token everytime.
- When using Ollama, no login is required to access and utilize the llama model.
"""

from huggingface_hub import login

# Read Hugging Face token from environment variable if available.
hf_token = os.getenv("HF_TOKEN")
if hf_token:
    login(token=hf_token)

# When running in a terminal, you can verify your login with:
# !huggingface-cli whoami

"""## TODO1: Set up the environment of Ollama

### Introduction to Ollama
- Ollama is a platform designed for running and managing large language models (LLMs) directly **on local devices**, providing a balance between performance, privacy, and control.
- There are also other tools support users to manage LLM on local devices and accelerate it like *vllm*, *Llamafile*, *GPT4ALL*...etc.

### Launch colabxterm
"""

# Commented out IPython magic to ensure Python compatibility.
# TODO1-1: You should install colab-xterm and launch it.
# Write your commands here.

# In Colab, you can install and load colab-xterm with:
# !pip install colab-xterm
# %load_ext colabxterm

# TODO1-2: You should install Ollama.
# You may need root privileges if you use a local machine instead of Colab.

# Commented out IPython magic to ensure Python compatibility.
# %xterm

# TODO1-3: Pull Llama3.2:1b via Ollama and start the Ollama service in the xterm
# Write your commands in the xterm

"""## Ollama testing
You can test your Ollama status with the following cells.
"""

# Setting up the model that this tutorial will use
MODEL = "llama3.2:1b" # https://ollama.com/library/llama3.2:3b
EMBED_MODEL = "jinaai/jina-embeddings-v2-base-en"

# Initialize an instance of the Ollama model
llm = Ollama(
    model=MODEL,
    # 視 Ollama 版本，透過 "options" 傳入
    temperature=0.0
)
# Invoke the model to generate responses
response = llm.invoke("What is the capital of Taiwan?")
print(response)

"""## Build a simple RAG system by using LangChain

### TODO2: Load the cat-facts dataset and prepare the retrieval database
"""

# In Colab you can download the cat-facts dataset with:
# !wget https://huggingface.co/ngxson/demo_simple_rag_py/resolve/main/cat-facts.txt

# TODO2-1: Load the cat-facts dataset (as `refs`, which is a list of strings for all the cat facts)
# Write your code here

refs = []
with open("cat-facts.txt", "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:
            refs.append(line)

print(f"Loaded {len(refs)} cat facts.")
print(refs[:3])

from langchain_core.documents import Document
docs = [Document(page_content=doc, metadata={"id": i}) for i, doc in enumerate(refs)]

# Create an embedding model
model_kwargs = {'trust_remote_code': True}
encode_kwargs = {'normalize_embeddings': False}
embeddings_model = HuggingFaceEmbeddings(
    model_name=EMBED_MODEL,
    model_kwargs=model_kwargs,
    encode_kwargs=encode_kwargs
)

# TODO2-2: Prepare the retrieval database
# You should create a Chroma vector store.
# search_type can be “similarity” (default), “mmr”, or “similarity_score_threshold”

from langchain.vectorstores import Chroma

# 建立 Chroma 向量資料庫，把剛剛的 docs 全部丟進去
vector_store = Chroma.from_documents(
    documents=docs,
    embedding=embeddings_model,
    collection_name="cat_facts"   # 只是取個名字，之後可以重用
)

# 從 Chroma 建一個 retriever 物件
retriever = vector_store.as_retriever(
    search_type="similarity",      # 先用最基本的相似度搜尋就好
    search_kwargs={"k": 5}         # 一次回傳前 5 筆最相似的 cat facts
)

# 簡單測試一下 retriever 是否正常
test_query = "How many sounds can a cat make?"
results = retriever.get_relevant_documents(test_query)

print(f"Top {len(results)} retrieved documents for query: {test_query}\n")
for i, d in enumerate(results, 1):
    print(f"[{i}] id={d.metadata.get('id')}: {d.page_content}\n")

"""### Prompt setting"""

from langchain_core.prompts import ChatPromptTemplate

# TODO3: Set up the `system_prompt` and configure the prompt.
system_prompt = """
You are a precise question answering assistant for cat trivia.

Your job:
- Use only the provided CONTEXT of cat facts.
- Answer the QUESTION in one short English sentence.
- Copy important facts (names, numbers, fractions) from the context exactly.
- When the question asks "How many / How much / How long", try to express the quantity
  both as a simple number and as **words**, e.g. "thirty-two muscles (32 muscles)" or
  "two thirds of the day".
- Avoid adding unnecessary paraphrases.
"""

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        (
            "human",
            """CONTEXT:
{context}

QUESTION:
{input}

Step 1: Based ONLY on the CONTEXT, answer the question in ONE short English sentence.
Do not mention that you are an AI. Do not say you don't know if the answer is clear in context.

Answer sentence:"""
        ),
    ]
)

label_template = """
You are writing the final short answer to a cat trivia question.

Question: {question}
Explanation: {answer_sentence}

Instructions:
- Give a VERY SHORT answer (1–4 words) that directly answers the question.
- Do NOT repeat the whole sentence. Just output the key phrase.
- If the question can be answered with yes/no (starts with:
  "Is", "Are", "Can", "Do", "Does", "Did", "Has", "Have", "Was", "Were"),
  answer with exactly "Yes" or "No".
- If the answer is a number or quantity (how many / how much / how long),
  write the number in SIMPLE ENGLISH WORDS, and include any word like
  "about", "around", "almost" if it appears in the Explanation.
  Examples:
  - "two thirds"
  - "about 100"
  - "five times"
  - "twenty five"
- For other questions, choose 1–4 key words (a short noun phrase) that
  best answers the question, e.g.:
  "taste mutation", "clowder", "Egyptian Mau", "Bast", "Cheshire Cat".

Output rules:
- ONE short phrase only.
- No bullet points.
- No numbering.
- No line breaks.
- No extra explanation.
"""

"""- For the vectorspace, the common algorithm would be used like Faiss, Chroma...(https://python.langchain.com/docs/integrations/vectorstores/) to deal with the extreme huge database."""

# TODO4: Build and run the RAG system
# TODO4-1: Load the QA chain
# You should create a chain for passing a list of Documents to a model.
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain

question_answer_chain = create_stuff_documents_chain(
    llm=llm,
    prompt=prompt,  
)

# TODO4-2: Create retrieval chain
# You should create retrieval chain that retrieves documents and then passes them on.
chain = create_retrieval_chain(
    retriever=retriever,
    combine_docs_chain=question_answer_chain,
)

from rank_bm25 import BM25Okapi

# refs 從 cat-facts.txt 讀進來的原始句子 list
tokenized_corpus = [doc.lower().split() for doc in refs]
bm25 = BM25Okapi(tokenized_corpus)

import numpy as np

def hybrid_retrieve(query: str, k_embed: int = 3, k_bm25: int = 3):
    # 1) embedding-based top-k
    embed_docs = retriever.get_relevant_documents(query)
    embed_ids = [d.metadata["id"] for d in embed_docs]

    # 2) BM25 top-k
    q_tokens = query.lower().split()
    scores = bm25.get_scores(q_tokens)
    top_bm25_ids = np.argsort(scores)[::-1][:k_bm25]

    # 3) 合併去重
    final_ids = []
    for i in embed_ids[:k_embed]:
        if i not in final_ids:
            final_ids.append(i)
    for i in top_bm25_ids:
        if int(i) not in final_ids:
            final_ids.append(int(i))

    # 4) 回傳 Document list
    return [docs[j] for j in final_ids]

# Question (queries) and answer pairs
# Write your code here
# Please load the questions_answers.txt file and prepare the `queries` and `answers` lists.
qa_path = "questions_answers.txt"

queries = []
answers = []

# 讀檔，把每一行去掉前後空白，順便丟掉空行
with open(qa_path, "r", encoding="utf-8") as f:
    lines = [line.strip() for line in f if line.strip()]

print("檔案中非空行數：", len(lines))

if len(lines) == 0:
    raise ValueError("questions_answers.txt 是空的，請確認檔案內容。")

# 每兩行是一組：第 1 行 = 問題，第 2 行 = 答案
for i in range(0, len(lines), 2):
    if i + 1 >= len(lines):
        print(f"第 {i} 行沒有對應答案行，請檢查檔案格式。")
        break
    queries.append(lines[i])
    answers.append(lines[i + 1])

print(f"Loaded {len(queries)} queries and {len(answers)} answers.")

# 有資料的話印一組範例看看
if queries:
    print("Example query:", queries[0])
    print("Example answer:", answers[0])

import re
from tqdm import tqdm
import json

all_records = []
num_correct = 0
hit_at_1 = 0
hit_at_5 = 0

def normalize_text(s: str) -> str:
    s = s.lower()
    s = ' '.join(re.findall(r'[a-z0-9]+', s))
    return s

def make_short_label(raw_label: str, question: str) -> str:
    """
    很保守的後處理：
    - yes/no 題：變成單純 "Yes" 或 "No"
    - 其他題：取第一個不是單純 Yes/No 的行，砍到最多 5 個詞
    """
    lines = [ln.strip() for ln in raw_label.splitlines() if ln.strip()]

    if not lines:
        return ""

    # 判斷是不是 yes/no 題
    is_yesno_q = bool(
        re.match(r"^(is|are|can|do|does|did|has|have|was|were)\b",
                 question.strip(), flags=re.IGNORECASE)
    )

    joined = " ".join(lines)
    low = joined.lower()

    if is_yesno_q:
        if "yes" in low and "no" not in low:
            return "Yes"
        if "no" in low and "yes" not in low:
            return "No"
        # fallback：看第一行第一個字
        first_word = lines[0].split()[0].lower()
        if first_word.startswith("y"):
            return "Yes"
        if first_word.startswith("n"):
            return "No"
        # 再不行就用第一行前幾個字
        tokens = lines[0].split()
        return " ".join(tokens[:3])

    # ---- 非 yes/no 題 ----
    # 如果第一行只有 "Yes"/"No"，就改用下一行
    idx = 0
    if lines[0].lower() in ("yes", "no") and len(lines) >= 2:
        idx = 1

    text = lines[idx]
    tokens = text.split()
    return " ".join(tokens[:5])


for i, query in tqdm(enumerate(queries), total=len(queries)):
    gt_answer = answers[i]

    # 1. 取回文件（RAG）
   # retrieved_docs = hybrid_retrieve(query, k_embed=3, k_bm25=3)
    #result = question_answer_chain.invoke({
    #"input": query,
    #"context": retrieved_docs,})
    #explanation = result

    result = chain.invoke({"input": query})
    explanation = result["answer"]
    retrieved_docs = result["context"]

    context_text = "\n".join(doc.page_content for doc in retrieved_docs)

    # 2. BM25 / hybrid 如果之後要加，可以在這裡改 retrieved_docs

    # 3. 產出短答案（兩階段：explanation -> label）
    label_prompt = label_template.format(
        question=query,
        answer_sentence=explanation
    )
    response = llm.invoke(label_prompt)
    raw_label = response.strip()

    label = make_short_label(raw_label, query)

    is_correct = normalize_text(gt_answer) in normalize_text(label)
    if is_correct:
        num_correct += 1

    # 5. 計算 Recall@1 / Recall@5
    correct_doc_id = i
    retrieved_ids = [doc.metadata.get("id") for doc in retrieved_docs]

    if len(retrieved_ids) >= 1 and correct_doc_id in retrieved_ids[:1]:
        hit_at_1 += 1
    if correct_doc_id in retrieved_ids[:5]:
        hit_at_5 += 1

    # 6. 紀錄所有題目的完整資訊（不管對錯都要存）
    all_records.append({
        "index": i,
        "question": query,
        "ground_truth": gt_answer,
        "model_answer": label,       # 用處理後 label
        "raw_label": raw_label,      # debug 用
        "explanation": explanation,
        "retrieved_ids": retrieved_ids,
        "retrieved_texts": [d.page_content for d in retrieved_docs],
        "is_correct": is_correct,
    })


N = len(queries)
accuracy = num_correct / N
recall_at_1 = hit_at_1 / N
recall_at_5 = hit_at_5 / N

print(f"Accuracy (回答是否含正解) : {accuracy:.3f}")
print(f"Recall@1 (top1 是否含正確句子) : {recall_at_1:.3f}")
print(f"Recall@5 (top5 是否含正確句子) : {recall_at_5:.3f}")

with open("rag_results.json", "w", encoding="utf-8") as f:
    json.dump(all_records, f, ensure_ascii=False, indent=2)

print("Saved detailed results to rag_results.json")

simple_records = []
for rec in all_records:
    simple_records.append({
        "Query": rec["question"],
        "Ground_Truth": rec["ground_truth"],
        "Prediction": rec["model_answer"],
    })

with open("NLP_HW4_NCCU_111307051.json", "w", encoding="utf-8") as f:
    json.dump(simple_records, f, ensure_ascii=False, indent=2)